const ActionTypes = {
        SAVE_MAP: "SAVE_MAP",
        SAVE_MARKERS: "SAVE_MARKERS",
        SAVE_LOCATIONS: "SAVE_LOCATIONS",
        PUSH_LOCATIONS: "PUSH_LOCATIONS",
        SET_CITY: "SET_CITY",
        RESET_CITY: "RESET_CITY",
        RESET_LOCATIONS: "RESET_LOCATIONS",
        REMOVE_MARKERS: "REMOVE_MARKERS",
        GET_CITIES: "SET_CITIES_LIST",
        TOGGLE_CITY_LIST: "TOGGLE_CITY_LIST",
        SET_CURRENT_LOCATION: "SET_CURRENT_LOCATION",
        BLOCK_LOADING: "BLOCK_LOADING",
        SET_TOKEN: "SET_TOKEN",
        SET_USER: "SET_USER"
};

export default ActionTypes;
