const ActionTypes = {
        SAVE_MAP: "SAVE_MAP",
        SAVE_MARKERS: "SAVE_MARKERS",
        SAVE_LOCATIONS: "SAVE_LOCATIONS",
        PUSH_LOCATIONS: "PUSH_LOCATIONS",
        SET_CITY: "SET_CITY",
        RESET_CITY: "RESET_CITY",
        RESET_LOCATIONS: "RESET_LOCATIONS",
        REMOVE_MARKERS: "REMOVE_MARKERS"
};

export default ActionTypes;
