export const SAVE_LOCATIONS = 'SAVE_LOCATIONS';
export const PUSH_LOCATIONS = 'PUSH_LOCATIONS';
export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';
export const SET_CURRENT_ADDRESS = 'SET_CURRENT_ADDRESS';
export const RESET_LOCATIONS = 'RESET_LOCATIONS';
export const BLOCK_LOADING = 'BLOCK_LOADING';
