export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS';
export const PUSH_LOCATIONS = 'PUSH_LOCATIONS';
export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';
export const SET_CURRENT_ADDRESS = 'SET_CURRENT_ADDRESS';
export const RESET_LOCATIONS = 'RESET_LOCATIONS';
export const BLOCK_LOADING = 'BLOCK_LOADING';
