export const FETCH_MARKERS = 'FETCH_MARKERS';
export const FETCH_MARKERS_SUCCESS = 'FETCH_MARKERS_SUCCESS';
export const RESET_MARKERS = 'RESET_MARKERS';
export const FIX_MARKERS = 'FIX_MARKERS';
export const UNFIX_MARKERS = 'UNFIX_MARKERS';
